---
title: "R Notebook"
output: html_notebook
---

```{r}
rm(list=ls()) # Clear workspace

library(readxl)
library(dplyr)
library(readr)
library(rlist)
library(tidyr)

# OG Movelist (combine with new moves)
movelist_txt <- read_delim("./Original Backup Text Files/moves.txt", delim = "\n", trim_ws = TRUE, col_names = FALSE)

# Read moves from xls
movelist_xls <- readxl::read_excel("PokeDB.xlsx", sheet = "Moves", col_types = "text")

# Filter only for moves set to be active
new_moves <- dplyr::filter(movelist_xls, Active == 1)

# Remove Non required columns from data frame
new_moves$Active <- NULL
new_moves$Notes <- NULL
new_moves$LenFlag <- NULL
#new_moves

# Start conversion to PBS format
row_data <- ""
data <- ""

value_list = c()

for (i in 1:nrow(new_moves)) {
 for (j in 1:ncol(new_moves)) {

      if (is.na(new_moves[[j]][i])) {
        #row_data <- ""
      } else {
        if (colnames(new_moves)[j] == "Title") {
        #  print("1")
          value_list <- c(value_list,"#-------------------------------")
          #row_data <- paste0("#-------------------------------","\n",new_moves[[j]][i])
          row_data <- paste0(new_moves[[j]][i])
        } else {
        #  print("2")
          row_data <- paste0(colnames(new_moves)[j]," = ",new_moves[[j]][i])
        }
       # print("3")
        #data <- paste0(data,"\n",row_data)
        value_list <- c(value_list,row_data)
        #print(data)
      }
 }

 }

# Combine new move details with old move file
combined_moves <- rbind(movelist_txt,data.frame(X1=value_list))

# Write out updated moves to PBS directory
lapply(combined_moves, write, "../PBS/moves.txt", append=FALSE, ncolumns=1)

##################################################################################
########## output pokemon ########################################################
# Read moves from xls
pkmnstats_xls <- readxl::read_excel("PokeDB.xlsx", sheet = "PkmnStats")

pkmnstats_xls$Name <- trimws(pkmnstats_xls$Name)
pkmnstats_xls$Abilities <- trimws(pkmnstats_xls$Abilities)
pkmnstats_xls$HiddenAbilities <- trimws(pkmnstats_xls$HiddenAbilities)
pkmnstats_xls$Types <- trimws(pkmnstats_xls$Types)
pkmnstats_xls$Pokedex <- trimws(pkmnstats_xls$Pokedex)
pkmnstats_xls$Category <- trimws(pkmnstats_xls$Category)

# Calculate percentile rank of points values
pkmnstats_xls <- pkmnstats_xls %>%
  mutate(HP_Pct = round((100 * rank(HP)/length(HP)),0), Attack_Pct = round((100 * rank(Attack)/length(Attack)),0), Def_Pct = round((100 * rank(Defence)/length(Defence)),0), SpAtk_Pct = round((100 * rank(`Special Attack`)/length(`Special Attack`)),0), SpDef_Pct = round((100 * rank(`Special Defence`)/length(`Special Defence`)),0), Speed_Pct = round((100 * rank(Speed)/length(Speed)),0))

###
## Load Pokemon PBS

og_pokemon_txt <- read_delim("./Original Backup Text Files/pokemon_tsouk.txt", delim = "\n", trim_ws = TRUE, col_names = FALSE)

# Split on Equals sign
og_pkmn_split <- data.frame(do.call('rbind', strsplit(as.character(og_pokemon_txt$X1),'=',fixed=TRUE)))
og_pkmn_split$X1 <- trimws(og_pkmn_split$X1)
og_pkmn_split$X2 <- trimws(og_pkmn_split$X2)

pkmn_name <- ''
og_pkmn_split$Name <- ''

# Add pokemon name to dataframe
for (i in 1:nrow(og_pkmn_split)) {
  if (og_pkmn_split$X1[i] == "Name") {
    pkmn_name <- og_pkmn_split$X2[i]
    og_pkmn_split$Name[i-2] <- pkmn_name
    og_pkmn_split$Name[i-1] <- pkmn_name
  }
  og_pkmn_split$Name[i] <- pkmn_name
}


# If any data in PkmnStats excel, add them in below (filter for no pokedex number)
new_pkmn_stats <- filter(pkmnstats_xls, is.na(`Pokedex Number`))

## Create Stats column (HP,Atk,Def,Speed,SpA,SpD)
new_pkmn_stats$BaseStats <- paste(new_pkmn_stats$HP,new_pkmn_stats$Attack,new_pkmn_stats$Defence,new_pkmn_stats$Speed,new_pkmn_stats$`Special Attack`,new_pkmn_stats$`Special Defence`,sep=',')

## Keep columns
keep_cols <- c('Name','BaseStats','Types','Abilities','HiddenAbilities','Pokedex','Category','Evolutions','WildItemCommon','WildItemUncommon','Moves')
#drop_cols <- c("HP","Attack","Defence","Special Attack","Special Defence","Speed","Base Stat Total")

pkmn_data = subset(new_pkmn_stats, select = keep_cols)
#as.data.frame(t(pkmn_data))

## Replace stats if match in pkmnstats_xls
#pkmn_data

# Use gather() to reshape the data
gather_pkmn <- gather(pkmn_data, key = "Column", value = "Value", -Name)

# Outer join on og data
pkmn_combine <- left_join(og_pkmn_split,gather_pkmn,by=c('Name'='Name','X1'='Column'))


## If there is data in the new column, replace the data in the old column

pkmn_combine$NewValue <- ifelse(!is.na(pkmn_combine$Value),pkmn_combine$Value,pkmn_combine$X2)
pkmn_combine$NewValue <- ifelse(pkmn_combine$NewValue==pkmn_combine$X1,'',pkmn_combine$NewValue)
pkmn_combine$NewValue <- gsub('#-------------------------------','',pkmn_combine$NewValue)
pkmn_combine$NewValue <- gsub('# See the documentation on the wiki to learn how to edit this file.','',pkmn_combine$NewValue)

pkmn_combine$NewValue <- ifelse(pkmn_combine$NewValue == "",'',paste0(' = ',pkmn_combine$NewValue))

pkmn_combine$Output <- paste0(pkmn_combine$X1,pkmn_combine$NewValue,sep="")

# Replace NA with 0
pkmn_combine[is.na(pkmn_combine)] <- ""

# Remove any fields forcibly nulled out by Excel file
pkmn_combine_drop_NONE <- filter(pkmn_combine, Value != 'NONE')

# Write out updated pokemon to PBS directory
lapply(as.data.frame(pkmn_combine_drop_NONE$Output), write, "../PBS/pokemon.txt", append=FALSE, ncolumns=1)

rm(list=ls())
```


```{r}

library("data.table")
og_pkmn_dex <- og_pkmn_split
setDT(og_pkmn_dex)[ , ID := .GRP, by = Name]

new_pkmn_text <- filter(og_pkmn_dex, ID >= 900 & Name != "Lechonk" & Name != "Oinkologne")

unique(new_pkmn_text$Name)
unique(gather_pkmn$Name)


## Find Pokemon only in Excel (and not in .txt file)
anti_join(new_pkmn_text,gather_pkmn,by=c('Name'='Name','X1'='Column'))


```

