---
title: "R Notebook"
output: html_notebook
---

```{r}
library(readxl)
library(dplyr)
library(readr)
library(rlist)
library(data.table)
library(tidyr) # Gather, Spread
library(stringr) ## str_sub

# Read Pokemon from xls
pkmnstats_xls <- readxl::read_excel("PokeDB.xlsx", sheet = "PkmnStats")

# Read in New Custom forms
pkmnforms_xls <- readxl::read_excel("PokeDB.xlsx", sheet = "PkmnForms")
pkmnforms_xls$Name <- paste0(str_sub(pkmnforms_xls$Name,end=-3)," - (",pkmnforms_xls$Form,")")
pk_forms <- pkmnforms_xls[,2:10]

# Combine Pokemon Data + Custom with New Custom Forms
pkmnstats_xls <- bind_rows(pkmnstats_xls,pk_forms)

## Clean data
pkmnstats_xls$Name <- trimws(pkmnstats_xls$Name)
pkmnstats_xls$Types <- trimws(pkmnstats_xls$Abilities)
pkmnstats_xls$HiddenAbilities <- trimws(pkmnstats_xls$HiddenAbilities)
pkmnstats_xls$Types <- trimws(pkmnstats_xls$Types)
pkmnstats_xls$Pokedex <- trimws(pkmnstats_xls$Pokedex)

# Calculate percentile rank of points values
pkmnstats_xls <- pkmnstats_xls %>%
  mutate(HP_Pct = round((100 * rank(HP)/length(HP)),0), Attack_Pct = round((100 * rank(Attack)/length(Attack)),0), Def_Pct = round((100 * rank(Defence)/length(Defence)),0), SpAtk_Pct = round((100 * rank(`Special Attack`)/length(`Special Attack`)),0), SpDef_Pct = round((100 * rank(`Special Defence`)/length(`Special Defence`)),0), Speed_Pct = round((100 * rank(Speed)/length(Speed)),0), BST_Pct = round((100 * rank(`Base Stat Total`)/length(`Base Stat Total`)),0))

## Import Smogon Tiers
smogon <- read_csv("smogon.csv")
smogon_tier <- subset(smogon, select = c('Name','Tier'))

pkmnstats_xls <- left_join(pkmnstats_xls, smogon_tier, by = c("Name"="Name"))
pkmnstats_xls$Tier[is.na(pkmnstats_xls$Tier)] <- "Untiered"

# Comparison
#compare <- dplyr::filter(pkmnstats_xls, Name %in% c("Edgarnator","Ragnarnator","Elsanator","Fenwrath"))
compare <- dplyr::filter(pkmnstats_xls, is.na(`Pokedex Number`))

## Get Percentiles for comparison pkmn
#pkmnstats_xls

comparison_frame <- data.frame(Name = NA, HP = NA, Attack = NA, Defence = NA, Special_Attack = NA, Special_Defence = NA, Speed = NA, Proximity = NA, BST_Proximity = NA, Tier = NA)

combined_frame <- comparison_frame

for (i in 1:nrow(pkmnstats_xls)) {

  ## Reset data frame
  comparison_frame <- data.frame(Name = '', HP = 0, Attack = 0, Defence = 0, Special_Attack = 0, Special_Defence = 0, Speed = 0, Proximity = 0, BST_Proximity = 0, Compare_to = '')
  
  for (j in 1:nrow(compare)) {
  if (pkmnstats_xls$Name[i] == compare$Name[j]) {
    # Do nothing
    
  } else {
    ## Compare data
    comparison_frame$Name = pkmnstats_xls$Name[i]
    comparison_frame$Compare_to = compare$Name[j]
    
    ## Perform calculations
    comparison_frame$HP <- compare$HP[j] - pkmnstats_xls$HP[i]
    comparison_frame$Attack <- compare$Attack[j] - pkmnstats_xls$Attack[i]
    comparison_frame$Defence <- compare$Defence[j] - pkmnstats_xls$Defence[i]
    comparison_frame$Special_Attack <- compare$`Special Attack`[j] - pkmnstats_xls$`Special Attack`[i]
    comparison_frame$Special_Defence <- compare$`Special Defence`[j] - pkmnstats_xls$`Special Defence`[i]
    comparison_frame$Speed <- compare$Speed[j] - pkmnstats_xls$Speed[i]
    comparison_frame$BST_Proximity <- compare$`Base Stat Total`[j] - pkmnstats_xls$`Base Stat Total`[i]
    comparison_frame$BST_Proximity_Abs <- abs(compare$`Base Stat Total`[j] - pkmnstats_xls$`Base Stat Total`[i])
    comparison_frame$Tier <- pkmnstats_xls$Tier[i]
    
    ## Calculate absolute difference
    comparison_frame$Proximity <- abs(comparison_frame$HP) + abs(comparison_frame$Attack) + abs(comparison_frame$Defence) + abs(comparison_frame$Special_Attack) + abs(comparison_frame$Special_Defence) + abs(comparison_frame$Speed)
  
  
    ### Create Dataframe of pokemon comparisons
  if (i == 1) {
    combined_frame <- comparison_frame
  } else {
    combined_frame <- rbind(combined_frame, comparison_frame)
  }
    
  }
    
  }
  
}

### Create PCT Frame and Stat Summary
keep_pct <- c('Name','HP_Pct','Attack_Pct','Def_Pct','SpAtk_Pct','SpDef_Pct','Speed_Pct','BST_Pct')
keep_stats <- c('Name','HP','Attack','Defence','Special Attack','Special Defence','Speed','Base Stat Total')

custom_pkmn <- filter(pkmnstats_xls, is.na(`Pokedex Number`))

pkmn_percentile <- subset(custom_pkmn, select = keep_pct)
pkmn_stats <- subset(custom_pkmn, select = keep_stats)

gpp <- gather(pkmn_percentile, key = "Stat", value = "Percentile", -`Name`)
gpp$Stat <- ifelse(gpp$Stat=="HP_Pct","HP",ifelse(gpp$Stat=="Attack_Pct","Attack",ifelse(gpp$Stat=="Def_Pct","Defence",ifelse(gpp$Stat=="SpAtk_Pct","Special Attack",ifelse(gpp$Stat=="SpDef_Pct","Special Defence",ifelse(gpp$Stat=="Speed_Pct","Speed",ifelse(gpp$Stat=="BST_Pct","Base Stat Total","")))))))
  
gps <- gather(pkmn_stats, key = "Stat", value = "Base Stats", -`Name`)

new_pkmn_summary <- left_join(gps, gpp, by = c("Name"="Name", "Stat" = "Stat"))
#filter(new_pkmn_summary, Name == "Tsoukinator")
```


```{r}
## Subject PKMN
subject <- "FoodBaby" #"Elsanator" #"Ragnarnator"# "Edgarnator"
# Filter to pkmn
subject_frame <- filter(combined_frame, tolower(Compare_to) == tolower(subject))
close_pokemon <- subject_frame[order(subject_frame$Proximity),]
bst_prox_pkmn <- subset(subject_frame[order(subject_frame$BST_Proximity_Abs),], select = c("Name","Tier","BST_Proximity","BST_Proximity_Abs"))
##### TIER RANKING #####
top50tiers <- head(close_pokemon,50) %>% group_by(`Tier`) %>% summarise(Count = n())
top50tiers[order(-top50tiers$Count),]
##### PERCENTILE RANKING ######
filter(new_pkmn_summary, tolower(Name) == tolower(subject)) # Stat Summary with Percentiles
##### NEAREST NEIGHBOURS #####
bst_prox_pkmn # Pkmn Closest in Base Stat Total
close_pokemon # Pokemon with stats closest to this one - Minus denotes subject has LESS in that stat area
```
### Changes
## Ragnarnator - Drop HP by 20, increase speed by 20, Increase special_attack by 5
## Elsanator - Increase speed by 5
## Edgarnator - Keep for now

#Ragnarnator current stats: 90	80	75	110	80	80	(515)
#Elsanator current stats: 75	90	70	100	70	110	(515)
#Edgarnator current stats: 120	90	115	60	85	60	(530)

#Ragnarnator modified stats: 90	80	75	110	80	80	(515)
#Elsanator modified stats: 75	90	70	100	70	110	(515)
#Edgarnator modified stats: 120	90	115	60	85	60	(530)


```{r}
####################################################
### OUTPUT UPDATED ALL POKEMON PERCENTILES FILE ####
####################################################

keep_cols <- c('Name','HP','Attack','Defence','Special Attack','Special Defence','Speed','Base Stat Total','HP_Pct','Attack_Pct','Def_Pct','SpAtk_Pct','SpDef_Pct','Speed_Pct','BST_Pct')

bst_summary <- subset(pkmnstats_xls, select = keep_cols)

## Import Smogon Tiers
smogon <- read_csv("smogon.csv")
smogon_tier <- subset(smogon, select = c('Name','Tier'))

bst_summary_tiers <- left_join(bst_summary, smogon_tier, by = c("Name"="Name"))
bst_summary_tiers$Tier[is.na(bst_summary_tiers$Tier)] <- "Untiered"

### Output to CSV
write_csv(x=bst_summary_tiers, file = "all_pokemon_percentiles.csv", append = FALSE)
```

